version: "3.4"
services:
  setup:
    build: docker/setup
    volumes:
      - .:/app

    #########################################
    #########################################
    ################ 修改这里 ################
    #########################################
    #########################################

    environment:
      #
      # QQ 账号
      QQ: 2434817339

      # QQ 密码
      QQ_PASS: Irt-vuN-h0U-QXM56789

      # 伪装登录设备
      # ANDROID_PHONE / ANDROID_PAD / ANDROID_WATCH / MACOS / IPAD
      DEVICE: IPAD

      # OpenAI session token
      SESSION_TOKEN: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..PIa8e0kYWRhfj9-P.cgY6XiIGYVcT8KFph7PkFaVmJrKmURn4_uoST4PiOW4Lw7SfN8veCh_30SAY5kSMG4opF4lHAliloLlqEld4Alia1d6GyhfLXUT1z0PZi7YSHbI5c1WSG8J0ARqKoxLLXwV-oMcVeUNyEyiZa6ydpgw5QH775Pj48JM7jHLz41uGwE5YwFREJCZlm-Dd2c241-PEEW2i63bsIrxxNCB0RqkQaHKNEnrwQ1NqBZqqUHEOMxkcIuu2altALBup5EHqt9YNErnHQKwdD_fSBFkb9Ac9n6xnVlwQ3W2TmLJ9eISvbxasfgkGvtvsc_AkDzfmKjYJFATPEfsXMtAlNDDzhiw_9GLeomN6-7Y6Zm3sCBYtyzMDhV8aUJF0FARDcvnq7XyQjtGm905t8XtjUZjOQs3x6xrqlKrQ6NTRQGwes4BIZj8sNdPi02gDccvitYjiwyanhVrCYUfaS-DmWXzwg0xwnkEzxTQJOrk-6wq0rrIKxG9O7dVDWQVjflGHmHNR6ofYsgUiCj6fp574t2a5tTNpB7u022aOwrNVDiV6Cy7rgHe1VoyHLTvKPIVUPi7CR82f2sOHRzaShGfRnR0W_RHGhx3ts4dNt79r3_ylxVPjC-6ZW5hTQ2_TSg-cFm_tMkSig34pJ2W4ESJ4yZsNk-QnSpQWpKktPf8dOxDt2c5Ako0PFdWrrKzE-D2ZAP28OHIEynWsPMz--qzAhnMgYSkUxWaNjq-wvWz2NtvD1Lqyb8IMbn78-37QKb1-zq7-ScTBE4mcHlJUrOi-XabXEze7IkpnM-3YHI3RxLjFNcs0FpUoLrETpVMLjPAaYNErKxbvUAHj7kHe5wf2-hmiCJ34MtQhgbAkQFONNI1k30UFlreM05vjcyN7q6zvmCf0rTCtQZvz2WuKe83wXR1HyxV1j89bytcMYvjfAfCp14PGJuKexh1aeRePZJRYqXlonEGRPSfeLjiMrEXE4oOpg4jpEhHem5Igq6j0jANAk1_A1ezk2XbQI2vXT_HgXmzhsKxxAbM-ou9vG9j2A7M2MeIrILGHPYT0Quwg6AEFgPCiGZXoU6UpfBFHTIc__UD91MSBCgd797_V44WAHutymeLg1mJDPYOieRbIM1hSP5YjvF0AKvRvpFpfRarVD5Gt5r5JoHNTLJay88jAprINqSyUOnYIUP4HjTCEe_7QRPGDZ16UIu0wGUoKkv0yDY480HPRIv4yeKt0tV64RLEpUbI3QnW-EwkkjmQzHod-AJX9PDTDlJOfH6T9UNzZE91L0e9VFxtdpr_hKMlzPHNUJ22iX1bx2PKQ8_MGvGt8n_afMJRfN7Z7fPFvYo2EI3dudex6DA-sG2xFLvt2y4EQtgmdqjtqghnN7Ly4jSpQBM3H83UN5OWiryWZsRZGretyXtarq2vbwaDFbri71TLFy5mIghtBrzN70CIT4DoHT1eiwX77X94IOzlF5VrnVG0JZUaOdLJ4HgA8rSqG1urqfR8KKINQYgN2g4Gq5690k-WCma4r7FCUQ_66ArU8rA2NlUmFOZGyGGyOXSveUX-sc4l6XlUIUmWAnZu8RGk-7Cgr46qaghrrI2aGQeUKNJPr_SF6fftQkWMhFzkUEQbGms4JBfmT_4QKjkHjNs3FZFvKeHwR5OoxgmePKWrPM-IgRbKIYMHFDbSywdNtS8WdHVf_Es5aQMqbUL0HxxT9A8dZQ1pPCm1l6j2WPbX7ShWNZoC6PjlE7fFaeECF1irti8fvCx2qfypFIEVKIKcOXjIK7NglU-X6Ij-GzJP-3iTaTBPOzM41_8xAxY3AlpT8FG4tQ5opQRbzft4ARLqSG0G9Y4cSE2fcbTIB5XjsLn0oEKGeNU7umgQNqvU0kAc7RW76nJpff6FyUm1qRMtShvSfAmTUp2OGK5vN-xkf8zqW85aFhZZP67Xl_O9_XyLh2prkW_wF4JQZmb0kdEmtPZZW1qbNwvYYhGkz4dcr6WIe0VSzLNl2uaJHNzvbXbQXeiYDpV_IT90B4UUtRQ-7ZHPUOVk1gIADxF_O_0sSzWuJXqh97kzIUJAnhMOEnX-gSi4Aa529VnjwWl4n1ksngFX0FylDM3tsoFTZ4Awf5kmwSI-1C5NAPDahGBnwZsewZpJ9TGp5TO0RTSqh3_QxGZsSKeyN-VvQmX6ZSpMv8u0oiNCPerw6-DSczrY73BfZAU7m3_y665_N-L36GvzyEHslMOQcQ0kWaK0ACOoU-kiwVCpFZRj0AyCtZtaSCHRXPsBCh-dwBRKqrLXAvIVstNzbiu4_Ow4MjvLOn5QpktTHrcPOfR9t1AooO0iJeys7RGirDgZlRxOz6Cjb67jZBQDt7oTgADqtCZFdF2UOMDTXN72cwTN8Rgxtu4pcIFBIVoT53JtFNJA94bp09fIFA_NXMGDvANpRi2gOSpHmiGysiBHgk88j3skKxKAmtNPqxTCj2SuyoHq-rMxVzyxZYZnW_4zqEW64UUIg_0owwkgg6LQIe7u8xP16MaI47b-pW8YmCULsLDg.mrjyHH046Gt4w6Y6SF5MnA

      # API KEY (如果你不知道这是什么，可以不用管)
      API_KEY: AnyRandomAPIKey

    #########################################
    #########################################
    ################ 到此为止 ################
    #########################################
    #########################################

  mirai:
    build: docker/mirai
    restart: always
    environment:
      LANG: "C.UTF-8"
    volumes:
      - ./mirai:/mirai
    networks:
      - mirai_network

  chatgpt:
    build: docker/chatgpt
    restart: always
    environment:
      LANG: "C.UTF-8"
      XPRA_PASSWORD: "xpra_password"
    volumes:
      - ./chatgpt/config.json:/app/config.json
      # - ./fonts:/app/fonts # 如果你想自定义字体，就解除注释
    networks:
      - mirai_network

networks:
  mirai_network:
